/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import {
  type ProcessorRecord,
  type IProcessorHostModule,
  type ProcessorFactory,
} from "document-drive/processors/types";

// Import other processor factories here as they are generated
import { searchIndexerProcessorFactory } from "./search-indexer/factory.js";

export const processorFactory = (module: IProcessorHostModule) => {
  // Initialize all processor factories once with the module
  const factories: Array<ProcessorFactory> = [];

  // Add all processor factories

  // Add other processors here as they are generated
  factories.push(searchIndexerProcessorFactory(module));

  // Return the inner function that will be called for each drive
  return async (driveId: string) => {
    const processors: ProcessorRecord[] = [];

    // Call each cached factory with the driveId
    for (const factory of factories) {
      processors.push(...(await factory(driveId)));
    }

    return processors;
  };
};
