export const globalTagsEnumOptions = [
  { value: "AVC", label: "AVC" },
  { value: "CAIS", label: "CAIS" },
  { value: "DAO_TOOLKIT", label: "DAO_TOOLKIT" },
  {
    value: "ECOSYSTEM_INTELLIGENCE",
    label: "ECOSYSTEM_INTELLIGENCE",
  },
  { value: "EXTERNAL_REFERENCE", label: "EXTERNAL_REFERENCE" },
  {
    value: "LEGACY_TERM_USE_APPROVED",
    label: "LEGACY_TERM_USE_APPROVED",
  },
  { value: "ML_DEFER", label: "ML_DEFER" },
  { value: "ML_LOW_PRIORITY", label: "ML_LOW_PRIORITY" },
  {
    value: "ML_SUPPORT_DOCS_NEEDED",
    label: "ML_SUPPORT_DOCS_NEEDED",
  },
  { value: "NEWCHAIN", label: "NEWCHAIN" },
  { value: "PURPOSE_SYSTEM", label: "PURPOSE_SYSTEM" },
  {
    value: "RECURSIVE_IMPROVEMENT",
    label: "RECURSIVE_IMPROVEMENT",
  },
  { value: "SCOPE_ADVISOR", label: "SCOPE_ADVISOR" },
  { value: "TWO_STAGE_BRIDGE", label: "TWO_STAGE_BRIDGE" },
];

export const globalScopeTagsEnumOptions = [
  { value: "ANON_WORKFORCE", label: "ANON_WORKFORCE" },
  { value: "AVC", label: "AVC" },
  { value: "CAIS", label: "CAIS" },
  { value: "DAO_TOOLKIT", label: "DAO_TOOLKIT" },
  { value: "ECOSYSTEM_INTELLIGENCE", label: "ECOSYSTEM_INTELLIGENCE" },
  { value: "EXTERNAL_REFERENCE", label: "EXTERNAL_REFERENCE" },
  { value: "FACILITATORDAO", label: "FACILITATORDAO" },
  { value: "INTERNAL_REFERENCE", label: "INTERNAL_REFERENCE" },
  { value: "LEGACY_TERM_USE_APPROVED", label: "LEGACY_TERM_USE_APPROVED" },
  { value: "ML_DEFER", label: "ML_DEFER" },
  { value: "ML_HIGH_PRIORITY", label: "ML_HIGH_PRIORITY" },
  { value: "ML_LOW_PRIORITY", label: "ML_LOW_PRIORITY" },
  { value: "ML_MED_PRIORITY", label: "ML_MED_PRIORITY" },
  { value: "ML_SUPPORT_DOCS_NEEDED", label: "ML_SUPPORT_DOCS_NEEDED" },
  { value: "NEWCHAIN", label: "NEWCHAIN" },
  { value: "P0_HUB_ENTRY_NEEDED", label: "P0_HUB_ENTRY_NEEDED" },
  { value: "PURPOSE_SYSTEM", label: "PURPOSE_SYSTEM" },
  { value: "RECURSIVE_IMPROVEMENT", label: "RECURSIVE_IMPROVEMENT" },
  { value: "SCOPE_ADVISOR", label: "SCOPE_ADVISOR" },
  { value: "SUBDAO_INCUBATION", label: "SUBDAO_INCUBATION" },
  { value: "SUBDAO_REWARDS", label: "SUBDAO_REWARDS" },
  { value: "TWO_STAGE_BRIDGE", label: "TWO_STAGE_BRIDGE" },
  { value: "V1_MIP", label: "V1_MIP" },
];

export const exploratoryTagsEnumOptions = [
  { value: "AVC", label: "AVC" },
  { value: "CAIS", label: "CAIS" },
  { value: "DAO_TOOLKIT", label: "DAO_TOOLKIT" },
  { value: "ECOSYSTEM_INTELLIGENCE", label: "ECOSYSTEM_INTELLIGENCE" },
  { value: "EXTERNAL_REFERENCE", label: "EXTERNAL_REFERENCE" },
  { value: "LEGACY_TERM_USE_APPROVED", label: "LEGACY_TERM_USE_APPROVED" },
  { value: "ML_DEFER", label: "ML_DEFER" },
  { value: "ML_LOW_PRIORITY", label: "ML_LOW_PRIORITY" },
  { value: "ML_SUPPORT_DOCS_NEEDED", label: "ML_SUPPORT_DOCS_NEEDED" },
  { value: "NEWCHAIN", label: "NEWCHAIN" },
  { value: "PURPOSE_SYSTEM", label: "PURPOSE_SYSTEM" },
  { value: "RECURSIVE_IMPROVEMENT", label: "RECURSIVE_IMPROVEMENT" },
  { value: "SCOPE_ADVISOR", label: "SCOPE_ADVISOR" },
  { value: "TWO_STAGE_BRIDGE", label: "TWO_STAGE_BRIDGE" },
]