name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Generate document models
      run: |
        pnpm script:generate-all
        pnpm generate ./docmodel-zips/AtlasFeedbackIssues.phdm.zip
      
    - name: Run tests
      run: pnpm test
